### ISSUE TITLE
Wrong Region

### ISSUE THREAD

**Issue by WhiteyFord** [arturfog/qtS3Browser#45]
Hi, firstly thanks for your effort:

Please advise if its possible for additional region options, namely 'ap-southeast-2' 

The error is: 

_Unable to parse ExceptionName: AuthorizationHeaderMalformed Message: The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'ap-southeast-2'_

I have tried to add the endpoint URL of https://s3.ap-southeast-2.amazonaws.com but get the same error.

Many thanks

**Comment by WhiteyFord** [comment]
Hi, further to this I have found the config file Regions.h and indeed the region is present, it appears that the region selector in the GUI is not scrollable, I am using Ubuntu 20.10

Thanks

**Comment by arturfog** [comment]
Hi, I've prepared fix in code, but I've some difficulties with preparation of snap (Ubuntu Store) package. Since last time I've build it, a lot has changed on snapcraft and travis CI. I'm solving issues one by one, I hope new packages will be ready soon.

**Comment by arturfog** [comment]
Good news, I was able to fix CI builds, and now new version 1.0.15 is ready. Until I'll test is fully it's available in edge channel.
You can install it using: snap install --edge qts3browser in terminal
